{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set bc = "batchcompute" %}
{% set bcv = "2.1.7" %}


package:
    name: {{ data.get('name') }}
    version: {{ data.get('version') }}

build:
    number: 0
    noarch: python
    # string: py_0
    script:
        - {{ PYTHON }} -m pip install --no-build-isolation --no-deps --no-cache-dir . https://pypi.io/packages/source/{{ bc[0] }}/{{ bc }}/{{ bc }}-{{ bcv }}.tar.gz

source:
    path: ..

requirements:
    host:
        - python >=3.7
        - pip
        - setuptools
    run:
        - python >=3.7
        - pip
        - setuptools
        - psutil >=5.7.0
        - prettytable >=3.2.0
        - configparser >=5.0.2

about:
    home: https://github.com/yodeng/runjob
    license: BSD
